-- ============================================================================
-- 支撑孪生体新范式多维数据融合分析框架原型系统 - 达梦 DM8 建表脚本
-- 01 - EAV (Entity-Attribute-Value) 核心数据模型
-- ============================================================================
-- 命名规范 (依《达梦数据库设计开发规范》):
--   表名: <业务简称>_<二级域>_<实体名称>, 大写 + 下划线
--   业务简称: TF (TwinFusion 孪生体融合框架)
--   二级域  : EAV (属性值通用存储)
--   主键   : ID, 使用 IDENTITY 自增, 不带业务含义
--   公共字段: CREATE_TIME, UPDATE_TIME (必须)
--   注释   : 每表每字段均用 COMMENT ON 子句
-- ============================================================================

-- 数据集: 一个 Excel/CSV 文件即一个数据集
CREATE TABLE "TF_EAV_DATASET" (
    "ID"              BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "DATASET_NAME"    VARCHAR(256) NOT NULL,
    "SOURCE_FILE"     VARCHAR(512),
    "SOURCE_TYPE"     VARCHAR(32)  DEFAULT 'EXCEL' NOT NULL,
    "DESCRIPTION"     VARCHAR(1024),
    "ROW_COUNT"       INT          DEFAULT 0,
    "DATA_DOMAIN"     VARCHAR(64),
    "CREATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX "IDX_TF_EAV_DATASET_NAME"   ON "TF_EAV_DATASET" ("DATASET_NAME");
CREATE INDEX "IDX_TF_EAV_DATASET_DOMAIN" ON "TF_EAV_DATASET" ("DATA_DOMAIN");

COMMENT ON TABLE  "TF_EAV_DATASET"                   IS '数据集: 一个 Excel/CSV 文件或一个逻辑批次';
COMMENT ON COLUMN "TF_EAV_DATASET"."ID"              IS '代理主键';
COMMENT ON COLUMN "TF_EAV_DATASET"."DATASET_NAME"    IS '数据集名称';
COMMENT ON COLUMN "TF_EAV_DATASET"."SOURCE_FILE"     IS '源文件路径';
COMMENT ON COLUMN "TF_EAV_DATASET"."SOURCE_TYPE"     IS '来源类型: EXCEL/CSV/API';
COMMENT ON COLUMN "TF_EAV_DATASET"."DESCRIPTION"     IS '描述';
COMMENT ON COLUMN "TF_EAV_DATASET"."ROW_COUNT"       IS '行数';
COMMENT ON COLUMN "TF_EAV_DATASET"."DATA_DOMAIN"     IS '业务域编码 (与 DATA/{域} 对齐)';
COMMENT ON COLUMN "TF_EAV_DATASET"."CREATE_TIME"     IS '创建时间';
COMMENT ON COLUMN "TF_EAV_DATASET"."UPDATE_TIME"     IS '更新时间';


-- 实体: 数据集中一行记录
CREATE TABLE "TF_EAV_ENTITY" (
    "ID"              BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "DATASET_ID"      BIGINT       NOT NULL,
    "ROW_INDEX"       INT          NOT NULL,
    "ENTITY_LABEL"    VARCHAR(512),
    "CREATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_EAV_ENTITY_DATASET" FOREIGN KEY ("DATASET_ID")
        REFERENCES "TF_EAV_DATASET" ("ID")
);
CREATE INDEX "IDX_TF_EAV_ENTITY_DATASET" ON "TF_EAV_ENTITY" ("DATASET_ID");
CREATE INDEX "IDX_TF_EAV_ENTITY_ROW"     ON "TF_EAV_ENTITY" ("ROW_INDEX");

COMMENT ON TABLE  "TF_EAV_ENTITY"                    IS '实体: 数据集中一行记录';
COMMENT ON COLUMN "TF_EAV_ENTITY"."ID"               IS '代理主键';
COMMENT ON COLUMN "TF_EAV_ENTITY"."DATASET_ID"       IS '所属数据集 ID';
COMMENT ON COLUMN "TF_EAV_ENTITY"."ROW_INDEX"        IS '原始行号';
COMMENT ON COLUMN "TF_EAV_ENTITY"."ENTITY_LABEL"     IS '实体标签 (可选)';
COMMENT ON COLUMN "TF_EAV_ENTITY"."CREATE_TIME"      IS '创建时间';
COMMENT ON COLUMN "TF_EAV_ENTITY"."UPDATE_TIME"      IS '更新时间';


-- 属性定义
CREATE TABLE "TF_EAV_ATTRIBUTE" (
    "ID"              BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "DATASET_ID"      BIGINT       NOT NULL,
    "ATTR_NAME"       VARCHAR(256) NOT NULL,
    "ATTR_CODE"       VARCHAR(128),
    "DATA_TYPE"       VARCHAR(32)  DEFAULT 'TEXT' NOT NULL,
    "ORD_INDEX"       INT          DEFAULT 0,
    "DESCRIPTION"     VARCHAR(512),
    "CREATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_EAV_ATTR_DATASET" FOREIGN KEY ("DATASET_ID")
        REFERENCES "TF_EAV_DATASET" ("ID"),
    CONSTRAINT "CK_TF_EAV_ATTR_TYPE" CHECK
        ("DATA_TYPE" IN ('TEXT', 'NUMBER', 'DATETIME', 'BOOL'))
);
CREATE INDEX "IDX_TF_EAV_ATTR_DATASET" ON "TF_EAV_ATTRIBUTE" ("DATASET_ID");
CREATE INDEX "IDX_TF_EAV_ATTR_NAME"    ON "TF_EAV_ATTRIBUTE" ("ATTR_NAME");

COMMENT ON TABLE  "TF_EAV_ATTRIBUTE"                 IS '属性定义';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."ID"            IS '代理主键';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."DATASET_ID"    IS '所属数据集 ID';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."ATTR_NAME"     IS '属性名称 (中文表头)';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."ATTR_CODE"     IS '属性编码';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."DATA_TYPE"     IS '数据类型: TEXT/NUMBER/DATETIME/BOOL';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."ORD_INDEX"     IS '列顺序';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."DESCRIPTION"   IS '描述';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."CREATE_TIME"   IS '创建时间';
COMMENT ON COLUMN "TF_EAV_ATTRIBUTE"."UPDATE_TIME"   IS '更新时间';


-- 属性值
-- 单表宽列, 以 VALUE_TEXT/VALUE_NUMBER/VALUE_DATETIME/VALUE_BOOL 四列并存;
-- 按 ATTR_ID 的 DATA_TYPE 决定读哪一列. 利于扩展, 代价是稀疏.
CREATE TABLE "TF_EAV_VALUE" (
    "ID"              BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "ENTITY_ID"       BIGINT       NOT NULL,
    "ATTR_ID"         BIGINT       NOT NULL,
    "VALUE_TEXT"      VARCHAR(4000),
    "VALUE_NUMBER"    DECIMAL(20, 6),
    "VALUE_DATETIME"  TIMESTAMP,
    "VALUE_BOOL"      CHAR(1)      CHECK ("VALUE_BOOL" IN ('0', '1')),
    "CREATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_EAV_VALUE_ENTITY" FOREIGN KEY ("ENTITY_ID")
        REFERENCES "TF_EAV_ENTITY" ("ID"),
    CONSTRAINT "FK_TF_EAV_VALUE_ATTR"   FOREIGN KEY ("ATTR_ID")
        REFERENCES "TF_EAV_ATTRIBUTE" ("ID")
);
CREATE INDEX "IDX_TF_EAV_VALUE_ENTITY" ON "TF_EAV_VALUE" ("ENTITY_ID");
CREATE INDEX "IDX_TF_EAV_VALUE_ATTR"   ON "TF_EAV_VALUE" ("ATTR_ID");

COMMENT ON TABLE  "TF_EAV_VALUE"                     IS '属性值 (四类型并存列)';
COMMENT ON COLUMN "TF_EAV_VALUE"."ID"                IS '代理主键';
COMMENT ON COLUMN "TF_EAV_VALUE"."ENTITY_ID"         IS '所属实体 ID';
COMMENT ON COLUMN "TF_EAV_VALUE"."ATTR_ID"           IS '属性 ID';
COMMENT ON COLUMN "TF_EAV_VALUE"."VALUE_TEXT"        IS '文本值';
COMMENT ON COLUMN "TF_EAV_VALUE"."VALUE_NUMBER"      IS '数值';
COMMENT ON COLUMN "TF_EAV_VALUE"."VALUE_DATETIME"    IS '日期时间';
COMMENT ON COLUMN "TF_EAV_VALUE"."VALUE_BOOL"        IS '布尔: 0/1';
COMMENT ON COLUMN "TF_EAV_VALUE"."CREATE_TIME"       IS '创建时间';
COMMENT ON COLUMN "TF_EAV_VALUE"."UPDATE_TIME"       IS '更新时间';
