-- ============================================================================
-- 02 - OM (Object Management) 对象抽取 + 三层架构关联
-- ============================================================================
-- 对应甲方核心需求 (1.md): 从 BA/DA/AA 表单抽取高层"对象" (项目/设备/资产...)
-- 并建立对象 <-> 概念实体/逻辑实体/物理实体的三层关联.
-- 本 DDL 是 MySQL bootstrap.sql 中 extracted_objects + object_entity_relations
-- 的达梦合规版. 命名与字段含义保持语义对齐, 命名规则按南网规范重写.
-- ============================================================================

-- 抽取对象
CREATE TABLE "TF_OM_EXTRACTED_OBJECT" (
    "ID"                     BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "OBJECT_CODE"            VARCHAR(128) NOT NULL,
    "OBJECT_NAME"            VARCHAR(256) NOT NULL,
    "OBJECT_TYPE"            VARCHAR(16)  DEFAULT 'CORE' NOT NULL,
    "DATA_DOMAIN"            VARCHAR(64)  NOT NULL,
    "DESCRIPTION"            VARCHAR(1024),
    "ATTR_COUNT"             INT          DEFAULT 0,
    "ENTITY_COUNT"           INT          DEFAULT 0,
    "CLUSTER_ID"             VARCHAR(64),
    "CLUSTER_SIZE"           INT          DEFAULT 0,
    "CONFIDENCE_SCORE"       DECIMAL(5, 4),
    "STATUS"                 VARCHAR(16)  DEFAULT 'ACTIVE' NOT NULL,
    "EXTRACTION_METHOD"      VARCHAR(32),
    "CREATE_TIME"            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "UK_TF_OM_OBJECT_CODE_DOMAIN" UNIQUE ("OBJECT_CODE", "DATA_DOMAIN"),
    CONSTRAINT "CK_TF_OM_OBJECT_TYPE"   CHECK ("OBJECT_TYPE"  IN ('CORE', 'DERIVED', 'AUXILIARY')),
    CONSTRAINT "CK_TF_OM_OBJECT_STATUS" CHECK ("STATUS"       IN ('ACTIVE', 'PENDING_MERGE', 'ARCHIVED'))
);
CREATE INDEX "IDX_TF_OM_OBJECT_DOMAIN" ON "TF_OM_EXTRACTED_OBJECT" ("DATA_DOMAIN");
CREATE INDEX "IDX_TF_OM_OBJECT_NAME"   ON "TF_OM_EXTRACTED_OBJECT" ("OBJECT_NAME");

COMMENT ON TABLE  "TF_OM_EXTRACTED_OBJECT"                   IS '抽取对象 (项目/设备/资产...)';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."ID"              IS '代理主键';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."OBJECT_CODE"     IS '对象编码 (OBJ_PROJECT/OBJ_ASSET...)';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."OBJECT_NAME"     IS '对象名称';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."OBJECT_TYPE"     IS '对象类型: CORE/DERIVED/AUXILIARY';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."DATA_DOMAIN"     IS '业务域编码';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."DESCRIPTION"     IS '描述';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."ATTR_COUNT"      IS '属性数';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."ENTITY_COUNT"    IS '关联实体数';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."CLUSTER_ID"      IS '聚类 ID (SBERT 聚类)';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."CLUSTER_SIZE"    IS '聚类大小';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."CONFIDENCE_SCORE" IS '置信度 0-1';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."STATUS"          IS '状态: ACTIVE/PENDING_MERGE/ARCHIVED';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."EXTRACTION_METHOD" IS '抽取方法: SBERT_LLM/KEYWORD_RULE';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."CREATE_TIME"     IS '创建时间';
COMMENT ON COLUMN "TF_OM_EXTRACTED_OBJECT"."UPDATE_TIME"     IS '更新时间';


-- 对象 <-> 三层实体关联 (核心)
CREATE TABLE "TF_OM_ENTITY_RELATION" (
    "ID"                 BIGINT         IDENTITY(1, 1) PRIMARY KEY,
    "OBJECT_ID"          BIGINT         NOT NULL,
    "ENTITY_LAYER"       VARCHAR(16)    NOT NULL,
    "ENTITY_NAME"        VARCHAR(512)   NOT NULL,
    "ENTITY_CODE"        VARCHAR(256),
    "RELATION_TYPE"      VARCHAR(16)    DEFAULT 'DIRECT' NOT NULL,
    "RELATION_STRENGTH"  DECIMAL(5, 4)  DEFAULT 0.7 NOT NULL,
    "MATCH_METHOD"       VARCHAR(32),
    "DATA_DOMAIN"        VARCHAR(64)    NOT NULL,
    "SOURCE_FILE"        VARCHAR(256),
    "VIA_CONCEPT_ENTITY" VARCHAR(512),
    "CREATE_TIME"        TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"        TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_OM_RELATION_OBJECT" FOREIGN KEY ("OBJECT_ID")
        REFERENCES "TF_OM_EXTRACTED_OBJECT" ("ID"),
    CONSTRAINT "CK_TF_OM_RELATION_LAYER"  CHECK ("ENTITY_LAYER"
        IN ('CONCEPT', 'LOGICAL', 'PHYSICAL')),
    CONSTRAINT "CK_TF_OM_RELATION_TYPE"   CHECK ("RELATION_TYPE"
        IN ('DIRECT', 'INDIRECT', 'DERIVED', 'CLUSTER')),
    CONSTRAINT "CK_TF_OM_RELATION_METHOD" CHECK ("MATCH_METHOD"
        IN ('EXACT', 'CONTAINS', 'SEMANTIC', 'LLM', 'SEMANTIC_CLUSTER'))
);
CREATE INDEX "IDX_TF_OM_REL_OBJECT" ON "TF_OM_ENTITY_RELATION" ("OBJECT_ID");
CREATE INDEX "IDX_TF_OM_REL_LAYER"  ON "TF_OM_ENTITY_RELATION" ("ENTITY_LAYER");
CREATE INDEX "IDX_TF_OM_REL_DOMAIN" ON "TF_OM_ENTITY_RELATION" ("DATA_DOMAIN");

COMMENT ON TABLE  "TF_OM_ENTITY_RELATION"                     IS '对象 <-> 三层实体关联';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."ID"                IS '代理主键';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."OBJECT_ID"         IS '对象 ID';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."ENTITY_LAYER"      IS '实体层: CONCEPT/LOGICAL/PHYSICAL';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."ENTITY_NAME"       IS '实体名称';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."ENTITY_CODE"       IS '实体编码';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."RELATION_TYPE"     IS '关系类型';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."RELATION_STRENGTH" IS '关系强度 0-1';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."MATCH_METHOD"      IS '匹配方法';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."DATA_DOMAIN"       IS '业务域';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."SOURCE_FILE"       IS '源文件';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."VIA_CONCEPT_ENTITY" IS '穿透路径 (逻辑层经由的概念实体名称)';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."CREATE_TIME"       IS '创建时间';
COMMENT ON COLUMN "TF_OM_ENTITY_RELATION"."UPDATE_TIME"       IS '更新时间';
