-- ============================================================================
-- 03 - LC (Lifecycle) / TR (Traceability) / MF (Mechanism Function) / AL (Alert)
-- ============================================================================
-- 命名: TF_LC_*, TF_TR_*, TF_MF_*, TF_AL_*
-- ============================================================================

-- ----------------- LC: 对象生命周期历史 -----------------
CREATE TABLE "TF_LC_OBJECT_HISTORY" (
    "ID"                  BIGINT       IDENTITY(1, 1) PRIMARY KEY,
    "OBJECT_ID"           BIGINT       NOT NULL,
    "LIFECYCLE_STAGE"     VARCHAR(16)  NOT NULL,
    "STAGE_ENTERED_AT"    TIMESTAMP,
    "STAGE_EXITED_AT"     TIMESTAMP,
    "ATTRIBUTES_SNAPSHOT" CLOB,
    "DATA_DOMAIN"         VARCHAR(64),
    "SOURCE_SYSTEM"       VARCHAR(128),
    "NOTES"               VARCHAR(2000),
    "CREATE_TIME"         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_LC_OBJECT" FOREIGN KEY ("OBJECT_ID")
        REFERENCES "TF_OM_EXTRACTED_OBJECT" ("ID"),
    CONSTRAINT "CK_TF_LC_STAGE" CHECK
        ("LIFECYCLE_STAGE" IN ('PLANNING','DESIGN','CONSTRUCTION','OPERATION'))
);
CREATE INDEX "IDX_TF_LC_OBJECT_STAGE" ON "TF_LC_OBJECT_HISTORY" ("OBJECT_ID","LIFECYCLE_STAGE");
CREATE INDEX "IDX_TF_LC_STAGE_TIME"   ON "TF_LC_OBJECT_HISTORY" ("LIFECYCLE_STAGE","STAGE_ENTERED_AT");

COMMENT ON TABLE  "TF_LC_OBJECT_HISTORY"                       IS '对象生命周期历史 (统一 4 阶段)';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."ID"                  IS '代理主键';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."OBJECT_ID"           IS '对象 ID';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."LIFECYCLE_STAGE"     IS '阶段: PLANNING/DESIGN/CONSTRUCTION/OPERATION';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."STAGE_ENTERED_AT"    IS '进入阶段时间';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."STAGE_EXITED_AT"     IS '离开阶段时间';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."ATTRIBUTES_SNAPSHOT" IS '阶段属性快照 (JSON 字符串)';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."SOURCE_SYSTEM"       IS '来源系统 (SAP/ERP/MES)';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."CREATE_TIME"         IS '创建时间';
COMMENT ON COLUMN "TF_LC_OBJECT_HISTORY"."UPDATE_TIME"         IS '更新时间';


-- ----------------- TR: 穿透式溯源链路 -----------------
CREATE TABLE "TF_TR_CHAIN" (
    "ID"            BIGINT        IDENTITY(1, 1) PRIMARY KEY,
    "CHAIN_CODE"    VARCHAR(128)  NOT NULL,
    "CHAIN_NAME"    VARCHAR(256),
    "CHAIN_TYPE"    VARCHAR(32)   DEFAULT 'CUSTOM' NOT NULL,
    "DATA_DOMAIN"   VARCHAR(64),
    "DESCRIPTION"   VARCHAR(2000),
    "CREATE_TIME"   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "UK_TF_TR_CHAIN_CODE" UNIQUE ("CHAIN_CODE"),
    CONSTRAINT "CK_TF_TR_CHAIN_TYPE" CHECK
        ("CHAIN_TYPE" IN ('FINANCIAL','PROCUREMENT','CONSTRUCTION','CUSTOM'))
);

COMMENT ON TABLE  "TF_TR_CHAIN"                IS '穿透式溯源链路定义';
COMMENT ON COLUMN "TF_TR_CHAIN"."ID"           IS '代理主键';
COMMENT ON COLUMN "TF_TR_CHAIN"."CHAIN_CODE"   IS '链路编码 (业务唯一)';
COMMENT ON COLUMN "TF_TR_CHAIN"."CHAIN_NAME"   IS '链路名称';
COMMENT ON COLUMN "TF_TR_CHAIN"."CHAIN_TYPE"   IS 'FINANCIAL/PROCUREMENT/CONSTRUCTION/CUSTOM';
COMMENT ON COLUMN "TF_TR_CHAIN"."DATA_DOMAIN"  IS '业务域';
COMMENT ON COLUMN "TF_TR_CHAIN"."DESCRIPTION"  IS '描述';
COMMENT ON COLUMN "TF_TR_CHAIN"."CREATE_TIME"  IS '创建时间';
COMMENT ON COLUMN "TF_TR_CHAIN"."UPDATE_TIME"  IS '更新时间';


CREATE TABLE "TF_TR_CHAIN_NODE" (
    "ID"            BIGINT        IDENTITY(1, 1) PRIMARY KEY,
    "CHAIN_ID"      BIGINT        NOT NULL,
    "NODE_ORDER"    INT           NOT NULL,
    "OBJECT_ID"     BIGINT,
    "ENTITY_LAYER"  VARCHAR(16),
    "ENTITY_NAME"   VARCHAR(512),
    "NODE_LABEL"    VARCHAR(256),
    "NODE_TYPE"     VARCHAR(16)   DEFAULT 'INTERMEDIATE' NOT NULL,
    "SOURCE_FILE"   VARCHAR(256),
    "SOURCE_SHEET"  VARCHAR(256),
    "METADATA"      CLOB,
    "CREATE_TIME"   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_TR_NODE_CHAIN" FOREIGN KEY ("CHAIN_ID")
        REFERENCES "TF_TR_CHAIN" ("ID"),
    CONSTRAINT "FK_TF_TR_NODE_OBJECT" FOREIGN KEY ("OBJECT_ID")
        REFERENCES "TF_OM_EXTRACTED_OBJECT" ("ID"),
    CONSTRAINT "CK_TF_TR_NODE_LAYER" CHECK
        ("ENTITY_LAYER" IN ('CONCEPT','LOGICAL','PHYSICAL')),
    CONSTRAINT "CK_TF_TR_NODE_TYPE"  CHECK
        ("NODE_TYPE" IN ('SOURCE','INTERMEDIATE','TARGET'))
);
CREATE INDEX "IDX_TF_TR_NODE_ORDER" ON "TF_TR_CHAIN_NODE" ("CHAIN_ID","NODE_ORDER");

COMMENT ON TABLE  "TF_TR_CHAIN_NODE"                IS '溯源链路节点';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."ID"           IS '代理主键';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."CHAIN_ID"     IS '所属链路 ID';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."NODE_ORDER"   IS '在链路中的顺序';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."OBJECT_ID"    IS '关联的抽取对象 ID';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."ENTITY_LAYER" IS 'CONCEPT/LOGICAL/PHYSICAL';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."NODE_TYPE"    IS 'SOURCE/INTERMEDIATE/TARGET';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."CREATE_TIME"  IS '创建时间';
COMMENT ON COLUMN "TF_TR_CHAIN_NODE"."UPDATE_TIME"  IS '更新时间';


-- ----------------- MF: 机理函数 -----------------
CREATE TABLE "TF_MF_FUNCTION" (
    "ID"                  BIGINT        IDENTITY(1, 1) PRIMARY KEY,
    "FUNC_CODE"           VARCHAR(128)  NOT NULL,
    "FUNC_NAME"           VARCHAR(256)  NOT NULL,
    "FUNC_TYPE"           VARCHAR(16)   NOT NULL,
    "CATEGORY"            VARCHAR(16)   DEFAULT 'BUSINESS' NOT NULL,
    "EXPRESSION"          CLOB          NOT NULL,
    "DESCRIPTION"         VARCHAR(2000),
    "SOURCE_OBJECT_CODE"  VARCHAR(128),
    "TARGET_OBJECT_CODE"  VARCHAR(128),
    "SEVERITY"            VARCHAR(16)   DEFAULT 'WARNING' NOT NULL,
    "IS_ACTIVE"           CHAR(1)       DEFAULT '1' NOT NULL,
    "DATA_DOMAIN"         VARCHAR(64),
    "CREATE_TIME"         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "UK_TF_MF_CODE"     UNIQUE ("FUNC_CODE"),
    CONSTRAINT "CK_TF_MF_TYPE"     CHECK ("FUNC_TYPE" IN ('FORMULA','RULE','THRESHOLD','VALIDATION')),
    CONSTRAINT "CK_TF_MF_CATEGORY" CHECK ("CATEGORY"  IN ('FINANCIAL','PHYSICAL','BUSINESS','QUALITY')),
    CONSTRAINT "CK_TF_MF_SEVERITY" CHECK ("SEVERITY"  IN ('INFO','WARNING','CRITICAL')),
    CONSTRAINT "CK_TF_MF_ACTIVE"   CHECK ("IS_ACTIVE" IN ('0','1'))
);
CREATE INDEX "IDX_TF_MF_SOURCE" ON "TF_MF_FUNCTION" ("SOURCE_OBJECT_CODE");
CREATE INDEX "IDX_TF_MF_TYPE_ACTIVE" ON "TF_MF_FUNCTION" ("FUNC_TYPE","IS_ACTIVE");

COMMENT ON TABLE  "TF_MF_FUNCTION"                       IS '机理函数定义 (公式/规则/阈值/校验)';
COMMENT ON COLUMN "TF_MF_FUNCTION"."ID"                  IS '代理主键';
COMMENT ON COLUMN "TF_MF_FUNCTION"."FUNC_CODE"           IS '函数编码 (业务唯一)';
COMMENT ON COLUMN "TF_MF_FUNCTION"."FUNC_TYPE"           IS 'FORMULA(公式)/RULE(规则)/THRESHOLD(阈值)/VALIDATION(校验)';
COMMENT ON COLUMN "TF_MF_FUNCTION"."CATEGORY"            IS 'FINANCIAL/PHYSICAL/BUSINESS/QUALITY';
COMMENT ON COLUMN "TF_MF_FUNCTION"."EXPRESSION"          IS '函数表达式 (JSON 字符串)';
COMMENT ON COLUMN "TF_MF_FUNCTION"."SEVERITY"            IS 'INFO/WARNING/CRITICAL';
COMMENT ON COLUMN "TF_MF_FUNCTION"."IS_ACTIVE"           IS '是否启用 0/1';
COMMENT ON COLUMN "TF_MF_FUNCTION"."CREATE_TIME"         IS '创建时间';
COMMENT ON COLUMN "TF_MF_FUNCTION"."UPDATE_TIME"         IS '更新时间';


-- ----------------- AL: 预警记录 -----------------
CREATE TABLE "TF_AL_ALERT_RECORD" (
    "ID"                  BIGINT        IDENTITY(1, 1) PRIMARY KEY,
    "FUNC_ID"             BIGINT        NOT NULL,
    "ALERT_LEVEL"         VARCHAR(16)   NOT NULL,
    "ALERT_TITLE"         VARCHAR(256),
    "ALERT_DETAIL"        VARCHAR(4000),
    "RELATED_OBJECT_ID"   BIGINT,
    "RELATED_ENTITY_NAME" VARCHAR(512),
    "TRIGGER_VALUE"       VARCHAR(2000),
    "THRESHOLD_VALUE"     VARCHAR(2000),
    "IS_RESOLVED"         CHAR(1)       DEFAULT '0' NOT NULL,
    "RESOLVED_BY"         VARCHAR(128),
    "RESOLVED_AT"         TIMESTAMP,
    "CREATE_TIME"         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_TIME"         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TF_AL_FUNC" FOREIGN KEY ("FUNC_ID") REFERENCES "TF_MF_FUNCTION" ("ID"),
    CONSTRAINT "CK_TF_AL_LEVEL"    CHECK ("ALERT_LEVEL" IN ('INFO','WARNING','CRITICAL')),
    CONSTRAINT "CK_TF_AL_RESOLVED" CHECK ("IS_RESOLVED" IN ('0','1'))
);
CREATE INDEX "IDX_TF_AL_LEVEL"   ON "TF_AL_ALERT_RECORD" ("ALERT_LEVEL","IS_RESOLVED");
CREATE INDEX "IDX_TF_AL_CREATED" ON "TF_AL_ALERT_RECORD" ("CREATE_TIME");

COMMENT ON TABLE  "TF_AL_ALERT_RECORD"                    IS '机理函数预警记录';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."ID"               IS '代理主键';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."FUNC_ID"          IS '触发的机理函数 ID';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."ALERT_LEVEL"      IS 'INFO/WARNING/CRITICAL';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."IS_RESOLVED"      IS '是否已处理 0/1';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."CREATE_TIME"      IS '创建时间';
COMMENT ON COLUMN "TF_AL_ALERT_RECORD"."UPDATE_TIME"      IS '更新时间';
